#!/bin/bash

cat <<EOF >"${HOME}/.tmux.conf"
################################################################################
#         # ANY EDITS MADE DIRECTLY TO THIS FILE WILL BE OVERWRITTEN #         #
#         ############################################################         #
#                                                                              #
# This .tmux.conf file is generated by 'install_tmux_config.sh'. Make desired  #
# changes to this file by modifying 'install_tmux_config.sh' and regenerating  #
#                                  this file.                                  #
################################################################################
#                                    Notes                                     #
################################################################################
# - You can use any unique prefix of a tmux command to run that command, e.g.  #
#   "bind" vs "bind-key" and "unbind" vs "unbind-key" (used here)              #
# - 'bind -r' means "this key may repeat". Using this option for resizing      #
#   windows means that I can hold the key to make course changes to window     #
#   size                                                                       #
# - 'bind -T' means "bind this key in the given key table". Key tables are     #
#   arbitrary (switch between them with 'switch-client -T ...') except for the #
#   *prefix* table and the *root* table.                                       #
#   - The *prefix* table is used for keys pressed after the tmux prefix, which #
#     is set to C-o in the first line of this config, and is where 'bind-key'  #
#     stores key bindings by default.                                          #
#   - The *root* table is used for keys pressed with no prefix; this table can #
#     be modified with 'bind-key -n ...'                                       #
################################################################################

set -g prefix C-o
bind -r C-o send-prefix

# vim-like pane resizing
bind -r C-k resize-pane -U
bind -r C-j resize-pane -D
bind -r C-h resize-pane -L
bind -r C-l resize-pane -R

# vim-like pane switching
bind -r k select-pane -U
bind -r j select-pane -D
bind -r h select-pane -L
bind -r l select-pane -R

# vim-like selection
unbind -T copy-mode-vi Space
unbind -T copy-mode-vi Enter
unbind -T copy-mode-vi v
bind -T copy-mode-vi v send-keys -X begin-selection
bind -T copy-mode-vi y send-keys -X copy-selection-and-cancel
# Automatically copy copied text to system clipboard using xsel
bind -T copy-mode-vi y send-keys -X copy-pipe-and-cancel "xsel -ib"
bind -T copy-mode-vi C-v send-keys -X rectangle-toggle
bind -T copy-mode-vi Escape send-keys -X clear-selection

# and now unbind the navigation keys we're no longer using
unbind Up
unbind Down
unbind Left
unbind Right

unbind C-Up
unbind C-Down
unbind C-Left
unbind C-Right

# re-bind window splitting
bind | split-window -h
bind - split-window -v
unbind '"'
unbind %

# bind ctrl-O ctrl-K to "clear-history" *inside* of tmux
#
# Note that tmux can't distinguish between C-k and C-K, unlike GNOME terminal,
# b/c tmux gets its keys over the terminal interface, and the terminal can only
# send ascii to programs that it's running. Per [1], C-<anything> just masks
# the sent key with 0x1F, which maps it to the lower portion of the ascii table
# (the control characters). Moreover, because lower-case and upper-case ascii
# letters only differ by a single bit (0x20), C-<key> and C-<KEY> both always
# map to the same control character in the bottom portion of the ascii table.
#
# Per https://stackoverflow.com/a/15471269, it may be possible to send more
# detailed modifier key info to tmux, but I haven't figured that out yet.
#
# [1] https://github.com/tmux/tmux/issues/674#issuecomment-263157843
bind C-k clear-history

# re-bind window selection (to match screen)
bind '"' choose-tree -w
unbind w

bind w command-prompt "join-pane -t ':%%'"

# Source .bashrc, .profile, etc
set-option -g default-command bash

# Use 265-bit color
set-option -g default-terminal "screen-256color"

# Save lots of history
set -g history-limit 1000000

# renumber windows when closed
set-option -g renumber-windows on

set-window-option -g mode-keys vi

# Don't close pane when repeatedly mashing Ctrl-C to stop something
set -g remain-on-exit on
EOF
