#!/bin/bash

cat <<EOF >"${HOME}/.gitconfig"
################################################################################
#         # ANY EDITS MADE DIRECTLY TO THIS FILE WILL BE OVERWRITTEN #         #
#         ############################################################         #
#                                                                              #
#  This .gitconfig file is generated by 'update_git_config.sh'. Make desired   #
#  changes to this file by modifying 'update_git_config.sh' and regenerating   #
#                                  this file.                                  #
################################################################################
EOF

############
# Identity #
############

# Don't set my email in my global config. I use different emails for different
# projects, and leaving it unset ensures I configure my email per-repo
# git config --global user.email "matthew.steffen@gmail.com"

git config --global user.name "Matthew Steffen"

###################
# Preferred Tools #
###################

git config --global diff.tool "meld"
git config --global merge.tool "meld"
git config --global core.editor "vim"

#####################
# Low-level options #
#####################

# convert CRLF (windows) to LF (linux/macOS) on commit but not the other way
# around
git config --global core.autocrlf "input"

# disables -F option in 'less' (which git sets automatically).
#
# -F causes 'less' to exit if its input is less than one screen. This causes me
# problems with 'git diff': 'git diff's output is usually longer than one page,
# so I get in the habit of hitting Ctrl-D after running 'git diff' to exit less,
# but when its output is occasionally shorter than that I hit Ctrl-D anyway and
# kill my terminal. Setting '-+F' here forces 'less' to run (and intercept my
# habitual Ctrl-D) even if its input is less than one page.
#
# Note: it's weird that this isn't in the pager section, but setting it here
# works and AFAIK this is the only place I can set it.
git config --global core.pager "less -+F"

###########
# Aliases #
###########

# Show a DAG in the terminal
git config --global alias.dag "log --decorate --oneline --graph"

# Runs the "gitk" command-line utility. I don't use this much, maybe I should
# remove it?
git config --global alias.tkdag "!gitk"

# Runs "gitdiff" command (in $HOME/bin/gitdiff), which lists all changed files
# and diffs them with the working dir in 'meld' (one tab per file). This is my
# preferred way to see diff
git config --global alias.d "! gitdiff"

# Run 'git difftool'. It's similar to gitdiff. I don't use this much; maybe I
# should remove it?
git config --global alias.dt "difftool -y"

# Git log but only for GitHub PRs. I'm not sure why the "#" has to be in double
# quotes, but it does.
git config --global alias.prs "log --min-parents=2 --grep='^Merge pull request '"#"'[0-9]\\+'"

git config --global alias.cur-branch "rev-parse --abbrev-ref HEAD"
git config --global alias.root "rev-parse --show-toplevel"

#################
# Pager options #
#################

# Don't use pager with git branch, which is almost always <1 page IME
git config --global pager.branch "false"
